Extended AES support
davedufresne/modern_snmp pull request #3
Opened 2024-08-21 14:14 UTC by ethan-ferguson-zetier

Hey! I extended support for AES to include AES192 and AES256, while not breaking compatibility with AES128, nor SHA1 or MD5. All relevant changes have been tested, verifying that the packets are privated correctly with Wireshark.

LocalizedKey had to be changed, but I have kept it's original functionality intact, only extending functionality. This is due to the localized key needing to be extended for AES192 and AES256.

2024-08-22 16:01 UTC, davedufresne requested changes
Thanks Ethan, great work! I just left few comments about details.

2024-08-22 16:01 UTC, davedufresne commented on src/snmp_usm/src/localized_key.rs
> +        while bytes.len() < 32 {
Instead of using a magic constant you could use a named constant to make it clearer what '32' represents.

2024-08-22 16:01 UTC, davedufresne commented on src/snmp_usm/src/localized_key.rs
> +                Self::key_from_passwd(if bytes.len() == 0 { passwd } else { &bytes }, engine_id);
Using `is_empty` is clearer and more explicit than `bytes.len() == 0`

2024-08-22 16:01 UTC, davedufresne commented on src/snmp_usm/src/priv_key/aes_priv_key.rs
> +        &key[..(BITS / 8)]
Same thing here, if you could use a named constant instead of `8`.

2024-08-23 13:28 UTC, ethan-ferguson-zetier commented on src/snmp_usm/src/localized_key.rs
> +        while bytes.len() < 32 {
Just added an "AES_256_KEY_LEN" constant

2024-08-23 13:28 UTC, ethan-ferguson-zetier commented on src/snmp_usm/src/priv_key/aes_priv_key.rs
> +        &key[..(BITS / 8)]
For this, it's just converting from bits to bytes. Would you like me to add this to a constant? Or would it be better to add a comment explaining what `8` is used for?

2024-08-23 14:50 UTC, davedufresne commented on src/snmp_usm/src/priv_key/aes_priv_key.rs
> +        &key[..(BITS / 8)]
That's fine, lets merge!

2024-08-23 14:52 UTC, merged